version: "2"
services:
  db:
    container_name: "database"
    image: mysql:5.5
    ports:
      - 3306:3306
  webapp:
    container_name: "webapp"
    image: goji-tomcat-app:latest
    build:
      context: ./tomcat
    depends_on:
      - db
    ports:
      - 8080:8080
    links:
      - db
