version: "2"
services:
  appdb:
    container_name: "database"
    image: mysql:5.5
  enviroment:
    MYSQL_DATABASE: gojidb
    MYSQL_USER: goji
    MYSQL_PASSWORD: goji123
  webapp:
    container_name: "webapp"
    image: maxor/goji-webapp
    depends_on:
      - appdb
    ports:
      - 8080:8080
    links:
      - appdb
